# Generated by Django 2.0.2 on 2018-09-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_auto_20180915_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
