# Generated by Django 2.0.2 on 2018-09-21 16:26

import csv
import os
from datetime import datetime

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import User

DATE = 0
WEIGHT = 1


def add_weights(apps, schema_editor):
    Weight = apps.get_model('weight', 'Weight')
    user = User.objects.get(username='Tom')
    dataset_file = os.path.join(settings.BASE_DIR, 'data/data.csv')

    with open(dataset_file) as dataset:
        reader = csv.reader(dataset)
        next(reader)  # ignore first row (headers)
        for entry in reader:
            Weight.objects.create(
                date=datetime.strptime(entry[DATE], '%Y-%m-%d').date(),
                weight=float(entry[WEIGHT]),
                body_fat=None,
                user_id=user.id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0003_auto_20180921_0733'),
    ]

    operations = [
        migrations.RunPython(add_weights),
    ]
